Tabelas "Area" e "Tags"
mattd-silva22/IC045-marketplace-ufba pull request #23
Opened 2024-10-17 01:41 UTC by mattd-silva22

### Issue relacionada

https://github.com/mattd-silva22/IC045-marketplace-ufba/issues/21

### Descrição
- Criei tabelas de "Area" e "Tags" e suas respectivas Seed.
- Organizei estrutura da Seed para facilitar futuras atualizações.

### Pendencias
- Trazer a seed de usuarios para novo padrão

2024-10-17 14:08 UTC, 1pedro commented on apps/api/infra/seed.ts
> +import { PrismaClient } from '@prisma/client';
Que tal por esse arquivo no mesmo lugar dos outros seeds?

`apps/api/prisma/agents.ts`

2024-10-17 14:11 UTC, 1pedro commented on apps/api/prisma/seed/fields.ts
> +export async function SeedFields() {
Ao invés de instanciar varios PrismaClient você poderia passar como parametro:

```suggestion
export async function SeedFields(prisma: PrismaClient) {
```

2024-10-17 14:12 UTC, 1pedro commented on apps/api/prisma/seed/tags.ts
> +export async function SeedTags() {
```suggestion
export async function SeedTags(prisma: PrismaClient) {
```

2024-10-17 14:12 UTC, 1pedro commented on apps/api/prisma/seed.ts
> +  await SeedTags();
```suggestion
  await SeedFields(prisma);
  await SeedTags(prisma);
```

2024-10-17 14:13 UTC, 1pedro commented on apps/api/prisma/seed/fields.ts
> +export async function SeedFields() {
Ao invés de instanciar varios PrismaClient você poderia passar como parametro:

```suggestion
export async function SeedFields(prisma: PrismaClient) {
```

2024-10-17 14:14 UTC, 1pedro commented on apps/api/prisma/seed/tags.ts
> +export async function SeedTags() {
Aqui também:

```suggestion
export async function SeedTags(prisma: PrismaClient) {
```

2024-10-17 20:16 UTC, mattd-silva22 commented on apps/api/infra/seed.ts
> +import { PrismaClient } from '@prisma/client';
certo, vou aplicar essa modificação.

2024-10-17 22:06 UTC, joel021 requested changes
Tá ótimo. Feito as modificações sugeridas por Pedro, podemos avançar!

2024-10-18 02:10 UTC, mattd-silva22 commented
Mudanças foram aplicadas

2024-10-19 14:50 UTC, merged

2024-10-19 14:51 UTC, joel021 commented on apps/api/prisma/migrations/20241017011504_create_tags_fields/migration.sql
> +CREATE TABLE "TbUsuario" (
Esqueceu de colocar em inglês kkk